version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:stable
    container_name: reverse-proxy
    depends_on:
      - rest-api
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  rest-api:
    image: node:current
    container_name: rest-api
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./rest-api:/home/node/app
    ports:
      - 5000
    command: "npm start"