version: '3.7'

# x-logging: &logging
#   logging:
#     driver: loki
#     options:
#       loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
#       loki-external-labels: job=dockerlogs,owner=paul,environment=development

services:
  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://host.docker.internal/grafana
      - GF_SERVER_DOMAIN=localhost
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000
  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail
    volumes:
      - ./promtail:/etc/config
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log:/var/log
    command: -config.file=/etc/config/config.yml


  broker:
    image: eclipse-mosquitto
    container_name: broker
    volumes:
      - broker:/mosquitto
    ports:
      - 1883:1883
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=America/Los_Angeles
    privileged: true
    ports:
      - 1880
    # networks:
    #   - node-red-net
    volumes:
      - node-red-data:/data
  rest-api:
    image: node:current
    container_name: rest-api
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./rest-api:/home/node/app
    ports:
      - 5000
    command: "npm start"
  reverse-proxy:
    image: nginx:stable
    container_name: reverse-proxy
    depends_on:
      - rest-api
      - node-red
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

volumes:
  broker:
  node-red-data:
  

# networks:
#   node-red-net: